services:
  - type: web
    name: hse-idt-backend
    runtime: python
    pythonVersion: 3.12
    rootDir: task_02_service
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0
