services:
  - type: web
    name: hse-idt-backend
    runtime: python
    pythonVersion: 3.12
    buildCommand: pip install -r task_02_service/requirements.txt
    startCommand: cd task_02_service && uvicorn main:app --host 0.0.0.0
